In [101]:
import numpy as np
from sklearn import datasets

In [102]:
bc = datasets.load_digits()
X=bc.data
Y=bc.target
X.shape,Y.shape

((1797, 64), (1797,))

In [103]:
yy=[]
xx=[]
for i in range(1797):
    if Y[i]==1:
        yy.append([0])
        xx.append(X[i])
    elif Y[i]==7:
        yy.append([1])
        xx.append(X[i])
YY=np.array(yy)
YY.shape
XX=np.array(xx)
X=XX
Y=YY

In [104]:
# # X = np.array([[0,0], [0,1], [1,0], [1,1]])
# # Y = np.array([[0,1,1,0]]).T
# # Y.shape
# Y=Y.reshape(1797,1)
# Y.shape

In [105]:
def sig(z):
    return 1/(1 + np.exp(-z))

In [106]:
def dsig(z):
    return sig(z)*(1 - sig(z))

In [107]:
wh = 2 * np.random.random((64,64)) - 1
wh2 = 2 * np.random.random((64,64)) - 1
bh = np.random.random((1, 64))* 2 - 1
bh2 = np.random.random((1, 64))* 2 - 1
wo = 2 * np.random.random((64,1)) - 1
bo = np.random.random(1)* 2 - 1

In [108]:
def forward(x, wh,wh2, wo, bh,bh2, bo):
    output0 = x
    hidden_layer_input = np.dot(output0, wh) + bh
    hidden_layer_output = sig(hidden_layer_input)
    
    output_layer_input = np.dot(hidden_layer_output, wh2) + bh2
    output = sig(output_layer_input)
    
    output_layer_input2 = np.dot(output, wo) + bo
    output2=sig(output_layer_input2)
    return output2

In [109]:
def train(X, Y, wh,wh2, wo, bh,bh2, bo, iterations, lr):
    for i in range(iterations):
        output0 = X
        hidden_layer_input = np.dot(output0, wh) + bh
        hidden_layer_output = sig(hidden_layer_input)
        
        hidden_layer_input2 = np.dot(hidden_layer_output, wh2) + bh2
        hidden_layer_output2 = sig(hidden_layer_input2)

        output_layer_input = np.dot(hidden_layer_output2, wo) + bo
        output = sig(output_layer_input)

        first_term_output = output - Y
        second_term_output = dsig(output_layer_input)
        first_two_terms_output = first_term_output * second_term_output
        
        second_term_hidden_layer2 = dsig(hidden_layer_input2)
        first_term_hidden_layer2 = np.dot(first_two_terms_output, wo.T)
        first_two_terms_hidden2 = first_term_hidden_layer2*second_term_hidden_layer2

        second_term_hidden_layer1 = dsig(hidden_layer_input)
        first_term_hidden_layer1 = np.dot(first_two_terms_hidden2, wh2.T)
        first_two_terms_hidden1 = first_term_hidden_layer1*second_term_hidden_layer1

        changes_wo = np.dot(hidden_layer_output2.T, first_two_terms_output)
        changes_wh2 = np.dot(hidden_layer_output.T, first_two_terms_hidden2)
        changes_wh = np.dot(output0.T, first_two_terms_hidden1)

        wh = wh - lr * changes_wh
        wh2 = wh2 - lr* changes_wh2
        wo = wo - lr * changes_wo

        changes_bh = np.sum(first_two_terms_hidden1, axis = 0)
        changes_bh2 = np.sum(first_two_terms_hidden2, axis = 0)
        changes_bo = np.sum(first_two_terms_output, axis = 0)

        bh = bh - lr * changes_bh
        bh2 = bh2 - lr* changes_bh2
        bo = bo - lr*changes_bo
    return wh, wh2, wo, bh, bh2, bo
        

In [110]:
wh, wh2, wo, bh, bh2, bo = train(X, Y, wh, wh2, wo, bh, bh2, bo, 1000, 0.01)

In [111]:
forward(X, wh,wh2, wo, bh,bh2, bo)

array([[  1.44699201e-03],
       [  9.97087833e-01],
       [  6.22419669e-04],
       [  9.96165015e-01],
       [  3.18633349e-03],
       [  9.97781220e-01],
       [  1.66216425e-03],
       [  9.92986191e-01],
       [  9.99684789e-01],
       [  1.47634834e-03],
       [  9.98467813e-01],
       [  5.84221052e-04],
       [  9.98306387e-01],
       [  8.99236897e-04],
       [  6.41918740e-04],
       [  9.98460567e-01],
       [  1.64492947e-03],
       [  9.99216897e-01],
       [  1.91963997e-03],
       [  1.84702311e-03],
       [  9.99194107e-01],
       [  4.34180904e-03],
       [  3.80896161e-03],
       [  9.89359769e-01],
       [  9.99474391e-01],
       [  9.99691661e-01],
       [  2.04871120e-02],
       [  9.99405116e-01],
       [  1.14998847e-02],
       [  9.90072008e-01],
       [  1.26671569e-02],
       [  9.99223758e-01],
       [  5.99225627e-03],
       [  9.99369600e-01],
       [  9.94466038e-01],
       [  1.23018248e-02],
       [  9.97976929e-01],
 

In [112]:
wh

array([[ 0.42737792, -0.51662638,  0.17536247, ...,  0.47680438,
         0.42416251,  0.15398002],
       [-0.01053446,  0.68462737,  0.06151213, ..., -0.14579216,
        -0.29817096, -0.45072151],
       [-0.75351586,  0.93168728,  0.90255392, ...,  0.10220008,
        -0.11108009,  0.54462804],
       ..., 
       [-0.13002118, -0.04209876, -0.885247  , ...,  0.6599565 ,
        -0.60852154, -0.52538255],
       [ 0.46996285,  0.24090899, -0.00498793, ...,  0.95624327,
         0.44022359, -0.12526246],
       [ 0.97513451,  0.71662224,  0.4777127 , ...,  0.29913905,
         0.04145288, -0.8671422 ]])

In [113]:
bh

array([[-0.25139058, -0.11263879,  0.71709275, -0.29284756,  0.41860189,
         0.41846071,  0.08875947, -0.12049135,  0.26102438,  0.76440219,
         0.64178414,  0.64667938, -0.86043214, -0.59035763, -0.08204564,
         0.81569144,  0.00714396,  0.56587132, -0.75875233, -0.66719833,
         0.58569965, -0.79963594,  0.55953462, -0.39149697,  0.20188434,
         0.5865116 ,  0.13972595, -0.54681249,  0.49984793, -0.66633848,
         0.2723455 , -0.25132212,  0.48530846, -0.03295511,  0.98484132,
        -0.54041138,  0.13234808,  0.87142296, -0.05670485,  0.36135874,
         0.09919435,  0.35052913, -0.09652735, -0.25518808,  0.6012665 ,
        -0.56791295,  0.23786283, -0.73755686,  0.08599243, -0.19508453,
         0.99641655,  0.76075353,  0.1418133 , -0.83421911, -0.26262902,
         0.08606704,  0.2241318 , -0.97584677,  0.22778867,  0.29963899,
        -0.82452182,  0.17710922, -0.89221037,  0.11122398]])

In [114]:
wo

array([[-0.91640717],
       [ 0.77720487],
       [ 0.2376967 ],
       [-0.5909366 ],
       [-0.76538636],
       [ 1.1317102 ],
       [-1.05289237],
       [ 0.91485817],
       [-0.68199961],
       [-1.00342939],
       [-0.58923418],
       [ 1.28446207],
       [ 0.07689989],
       [-1.10852559],
       [ 1.50020619],
       [-0.6241319 ],
       [-0.25308175],
       [ 0.69636788],
       [-0.50630006],
       [ 0.44424566],
       [ 0.40944199],
       [ 0.11798433],
       [ 0.91261631],
       [ 0.21757625],
       [-1.14096443],
       [-0.03817194],
       [-0.56212905],
       [-0.57350008],
       [-0.79749649],
       [ 0.96091574],
       [ 1.0874567 ],
       [ 0.75475387],
       [-0.03265216],
       [-0.96040642],
       [-0.18979313],
       [-1.02436565],
       [ 0.45835653],
       [ 0.58929764],
       [ 0.51547633],
       [-0.44760761],
       [ 0.44509426],
       [ 0.60580817],
       [-0.54269196],
       [-0.74473125],
       [-0.27023397],
       [ 0

In [115]:
bo

array([-0.45348163])

In [116]:
Y

array([[0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
    

In [120]:
result =[]
yo = forward(X, wh,wh2, wo, bh,bh2, bo)
for i in range(len(yo)):
    if yo[i]<=0.5:
        result.append([0])
    if yo[i]>0.5:
        result.append([1])


In [122]:
from sklearn.metrics import confusion_matrix

In [123]:
print(confusion_matrix(y_true = Y,y_pred = result))

[[182   0]
 [  0 179]]
